name: CI

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - run: cargo build --tests --benches --examples --all-targets

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - run: cargo check --tests --benches
    - run: cargo test

  miri:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install nightly --profile minimal --component miri
    - run: cargo +nightly miri test
      env:
        RUSTFLAGS: -Zrandomize-layout
        MIRIFLAGS: -Zmiri-strict-provenance -Zmiri-symbolic-alignment-check

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal --component rustfmt
    - run: cargo fmt --check
